precice/aste

- src/eval_mesh.py
- src/mesh_io.py
`eval_mesh.py` was hard to understand. Now it's easy. Also vtk is now only required if it is used.
> Simplify eval_mesh.py, make vtk optional

- contrib/demo.sh
- contrib/timestep-demo/clean.sh
- contrib/timestep-demo/timesteps-precice.xml
- contrib/timestep-demo/timesteps.py
- docs/README.md
- src/common.cpp
- src/mesh_io.py
- src/partition_mesh.py
- src/preciceMap.cpp
Enable multiple timesteps with aste. Major changes:
- Meshes are given in the format `--mesh example` to `preciceMap`, which then searches for `example.dt1`, `example.dt2`,...
- `partition_mesh` now works on multiple meshes as well. This is done by using the first mesh for determining a partition and applying it to every mesh given.
- `partition_mesh` can receive a vtk tag with the `--tag` option. This enables easy extraction of data read from vtk exports of preCICE.
- `demo.sh` was broken (is fixed now)
> Multiple timesteps

- CMakeLists.txt
VTK version higher than 8.9 requires a different CMake configuration
This PR provides a more sophisticated CMake configuration.
> Fix VTK Cmake configuration for VTK version > 8.90.0

- src/vtk_calculator.py
This update is related to Issue #36 
The previous script `eval_mesh` highly depended on `mesh_io` this update to VTK Calculator makes it a standalone script and provides missing functionalities. Which will replaces `eval_mesh`
In normal mode, it calculates function `f : (R³) -> R` and append to mesh file.
Example usage 
`./vtk_calculator.py bunny.vtk 'coordsX+coordsY'  -t "x+y" ` -> Calculates function `f=x+y` on mesh and save with datanamed `x+y`
In diff mode, it calculates function and compares with given data array.
`./vtk_calculator.py bunny.vtk '2*coordsX+2*coordsY'  -t "2x+2y" -d -s -it "x+y"` -> Calculates function `f=2x+2y` on mesh compares with datanamed `x+y` prints report and save json file. Appends calculated funciton `2x+2y` to mesh.
> Update VTK Calc

- src/join_mesh.py
This is almost a total replacement to the old mesh joiner.
Reads `vtu` files and join into a `vtu` or `vtk` file.
If recovery file is given preserves original mesh order and cells else appends partition-wise.
Supports all vector and scalar data preserve all of them
Closes [#35 ](https://github.com/precice/aste/issues/35)
> Fix Join Mesh

- src/partition_mesh.py
This PR fix mesh partitioner mentioned in issue #34 : 
Now it works without `mesh_io`. Able to work as a standalone script.
- Only accepts 1 `scalar` data in the partitioned mesh. It should be specified by `--tag` flag.
- Accepts both `vtu` and `vtk` files as input. 
- Writes output to a directory `outmeshname` and outputs are named as `outmeshname_r<>.vtu`
- A sample usage is:
- `/partition_mesh.py rbc_fill.vtk -n 4 -t "MyScalar"`
- There is no other change in partitioning or recovery data
> Fix Mesh Partitioner 

- src/vtk_calculator.py
There was a bug in `vtk_calculator`
If `intag` is given it is not used in diff mode. 
It is fixed by this PR.
> Fix bug intag is not used if it is given

- src/join_mesh.py
The number of components is not set before inserting data into the array was missing. It causes an error if one has vector data.
This PR fixes this bug mentioned in #55
> Fix Bug Mesh Joiner (Vector Data, No Cell, Missing GlobalIDs)

- src/vtk_calculator.py
The difference mode was buggy. This PR fixes/improves followings
- If a dataname can be interpreted as a function it was considered as a function it is fixed.
- There is no check for if a given dataname exist in the dataset(VTK file) this security added
- A naive implementation is used for `numpy_to_vtk` and `vtk_to_numpy` operations 
Fixes the problems in #59
> Fix and Improvements for vtk_calculator

- src/mesh.cpp
- src/mesh.hpp
- src/tests/read_test.cpp
- src/tests/testing.cpp
- src/tests/testing.hpp
- src/tests/write_test.cpp
After the mapping process using `preciceMap` except mapped data all of the datasets were not transferred to the output mesh.
In this fix, the input mesh file is used as a base for output mesh and only mapped data will be added to the input mesh. All other datasets will be preserved in this way.
> Fix missing data after mapping 

- src/join_mesh.py
- src/partition_mesh.py
- src/vtk_calculator.py
Solves #56 
All scripts use the same CLI input style
| Input Arg | Explanation                       |
| --------- | --------------------------------- |
| --mesh    | Input Mesh                        |
| --output  | Output Mesh                       |
| --data    | Data Modified/Calculatated/Mapped |
```bash
mpirun -n 2 preciceMap -v -p B --mesh coarse_mesh --output mapped/mapped --data "x + y"
partition_mesh.py --mesh 0.01.vtk -n 2 -o coarse_mesh
join_mesh.py --mesh mapped/mapped -o result.vtk -r recovery.json
vtk_calculator.py --mesh result.vtk -f x+y --data difference --indata "x + y" --diff
```
> Satisfy Consistency in CLI

- src/mesh.cpp
- src/mesh.hpp
`preciceMap` was only looking for `vtk` extension (VTK Legacy Format) in serial case this PR allows it to take `vtu` files  (VTKXML Format) too in serial cases.
Closes #65
> Support for `vtu` files in serial case

- src/join_mesh.py
- src/mesh.cpp
- src/partition_mesh.py
- src/vtk_calculator.py
As discussed in https://github.com/precice/aste/issues/63 VTK ASCII  writer does not provide sufficient precision for `double` datatype in ASCII mode. This PR changes the output format of all ASTE tools to binary.
> Change outputs from ASCII to Binary

- src/common.cpp
The default config filename for all tutorials is `precice-config.xml`, changes `preciceMap` to obey this convention.
> Change default config name

- .github/workflows/aste_ci.yml
so that we have a better overview of warnings and different compiler behavior.
Debatable `-Wall -Wextra` (also considering precice). @fsimonis any opinion?
> Add clang build and make CI fail on warnings

- src/join_mesh.py
- src/partition_mesh.py
As mentioned in #79, having many mesh in one directory is an issue due to recovery file name 
This PR change the recovery filename from  `recovery.json` to `<mesh_prefix>_recovery.json` so that they can easily be identified.
Closes #79
> Change recovery file export name

- requirements.txt
- src/join_mesh.py
- src/partition_mesh.py
- src/vtk_calculator.py
ASTE was lack of `requirement.txt` which specifies the required packages for python tools.
This PR adds a `requirements.txt` to ASTE.
Also, imported modules were not ordered and separated in tools, they have sorted alphabetically and separated as built-in system modules and imported side modules.
> Add python requirements

- src/modes.cpp
ASTE Naming convention was not obey preCICE naming convention. This PR adopt preCICE naming convention
> Adopt preCICE naming convention

- src/vtk_calculator.py
sympy is a relatively huge package and not required if a user doesn't need to work with gradient mapping. This PR makes sympy an optional dependency for `vtk_calculator.py`
> Make sympy optional for VTK calculator

- src/mesh.cpp
- src/mesh.hpp
- src/modes.cpp
- src/utilities.cpp
- tests/read_test.cpp
- tests/testing.cpp
- tests/testing.hpp
- tests/write_test.cpp
ASTE was configuring mesh connectivity even if it is not required at all. Now it would only load it when it is required.
Also provides tri and quads only in 3D cases not in 2D cases.
> Load and configure connectivity data only if required

- .github/workflows/indent.yml
Clang CI was only checking `*.cc` and `*.h` files which is weird since main repo mainly consist of `*.cpp` and `*.hpp` files.
This PR changes extensions to `*.c*` and `*.h*`
> Change file extensions for clang-format CI

- src/partition_mesh.py
see issue #123 
On centOS 7 (red hat based distribution) the directory containing libraries on 64 system are called lib64. But partition_mesh.py only looks into "../lib". I modified the script partition_mesh.py to look into and lib and lib64.
Works on CentOS 7.9.
Regards
> partition_mesh.py does not find libmetisAPI.so under lib64

- tools/mapping-tester/plotconv.py
When plotting memory consumption with the mapping tester, units weren't shown.
> Fixed missing units in plotconv.py

- CMakeLists.txt
This PR limits the required VTK components to the minimal requires set, which prevents pulling in OpenCV etc as dependencies.
> Limit VTK components

- .github/workflows/aste_ci.yml
- CMakeLists.txt
- tests/example/lci_2d/clean.sh
- tests/example/lci_3d/clean.sh
- tests/example/nn/clean.sh
- tests/example/nng_scalar/clean.sh
- tests/example/nng_vector/clean.sh
- tests/mapping-tester-example/clean.sh
This PR adds the provided examples to ctest.
Example tests are labelled `example`, so they can be skipped using `ctest -LE example`.
Each test consists of a test and a setup fixture which runs the `clean.sh` script of the test. This allows to check the output of a test.
New examples need to be added to the `_examples` list in the `CMakeLists.txt`.
> Add examples to CTest

- CMakeLists.txt
- src/modes.cpp
- src/modes.hpp
- src/utilities.cpp
For Nearest Neighbour Gradient and Tetra support, the requirement for preCICE was at least 2.5.0, and checks have been done using CMake. As preCICE offers, new versioning macros use them to detect the preCICE version instead of the usage of CMake.
> Move version detection for NNG and Tetra Support to code

- src/precice-aste-evaluate
In the gradient calculation, parenthesis was missing which led to a wrong calculation.
eg.
`(y-x)^2` should have a gradient `(2*x-2y)*iHat+(-2*x+2y)*jHat+0*kHat`  but get a gradient `2*x - 2*y*iHat+-2*x + 2*y*jHat+0*kHat` as a function which is not a vector equivalent to `-2*y*iHat+2*y*jHat+0*kHat + (2*x-2*x)` which is not a vector.
* [] I updated potential breaking changes in the tutorial [`precice/tutorials/aste-turbine`](https://github.com/precice/tutorials/tree/develop/aste-turbine).
> Fix gradient calculations

- docs/README.md
- examples/lci_2d/precice-config.xml
- examples/lci_3d/precice-config.xml
- examples/nn/precice-config.xml
- examples/nng_scalar/precice-config.xml
- examples/nng_vector/precice-config.xml
- examples/replay_mode/precice-config.xml
- src/common.cpp
- src/logger.cpp
- src/logger.hpp
- src/modes.cpp
- src/precice-aste-run.cpp
- tools/mapping-tester/config-template.xml
- tools/mapping-tester/generate.py
- tools/split-mesh-error/elasticTube/precice-config.xml
This PR changes the ASTE logger to:
* Tags log entries from `ASTE` using the constant boolean attribute `ASTE`.
* ~~Output only ASTE log entries by filtering `... and %ASTE%` in the sink.~~
* Adds additional attributes for `Participant` and `Rank`. This allows to distinguish log entries when running ASTE in parallel.
~~After this, preCICE will still output ASTE logs by default. A similar change will soon be merged in preCICE itself.
Until then, we can configure a log filter in preCICE `... and not %ASTE%` to remove ASTE log entries from the preCICE log.~~
_edit:_ ASTE will now handle logs from both preCICE and ASTE.
preCICE configs should disable all sinks by defining `<log enabled="false"></log>`
Related to #73
> Handle ASTE and preCICE logging

- CMakeLists.txt
- src/mesh.cpp
- src/mesh.hpp
- src/utilities.hpp
- tests/write_test.cpp
As a result of bumping to C++17, there is no need to boost::filesystem,  instead, STL implementation can be used. 
This PR changes filesystem libraries to STL implementation.
> Change boost::filesystem to std::filesystem

- src/precice-aste-join
- src/precice-aste-partition
Given the accuracy of our mapping methods, we need double precision to evaluate the accuracy well enough and exceed (in my experiment) the threshold of 1e-8.
> Fix vertex resolution in partitioner and joiner

- tools/mapping-tester/generate.py
which is more robust if time is not installed (disk-less mode on some HPC systems) and time is not installed in /usr
> Use env time to bypass built-in time instead of /usr/bin

- CMakeLists.txt
The test executable is called `testing` is clashes with Cmake testing directory.  `test` is located for Cmake itself. This PR changes the test executable to `precice-aste-test`
> Change test name from test to precice-aste-test

- .github/workflows/aste_ci.yml
> Try manual installation of VTK

- CMakeLists.txt
- changelog-entries/194.md
- **Enable Boost policy**
- **Fix linker errors when using boost from config**
> Fix Boost CMake usage

- changelog-entries/196.md
- src/modes.cpp
This PR changes the mapper of ASTE to abort if no mesh was found.
Currently, the executable SEGFAULTS, which is a bit dramatic.
> Fix SEGFAULT on missing mesh

- examples/run-all.sh
* <del> I updated the documentation in `docs/README.md`. </del>
* <del>  I updated potential breaking changes in the tutorial [`precice/tutorials/aste-turbine`](https://github.com/precice/tutorials/tree/develop/aste-turbine).</del>
Related to #199
> Make `run-all` script for examples more robust

- docs/README.md
The dependency from preCICE was already listed before, but no instructions on how to get preCICE were included.
Closes #204
> Highlight dependency from preCICE more clear

- CODE_OF_CONDUCT.md
- changelog-entries/205.md
- docs/CONTRIBUTING.md
Adds a `CODE_OF_CONDUCT` and `CONTRIBUTING` guidelines. Closes #203 
<del> I added a test to cover the proposed changes in our test suite. </del>
<del>I updated potential breaking changes in the tutorial [`precice/tutorials/aste-turbine`](https://github.com/precice/tutorials/tree/develop/aste-turbine). </del>
> Community guidelines

- tools/mapping-tester/gatherstats.py
This PR changes gatherstats to use scopes for extracting timings from the profiling data, making it robust against the introduction of additional scopes in between.
Related to https://github.com/precice/precice/pull/2066
> Add scoping support to gathering events

- .github/workflows/aste_ci.yml
This PR uses the new ASTE CI image https://hub.docker.com/r/precice/ci-aste which is based on `precice/precice:nightly` and installs a _working_ version of VTK from source.
https://github.com/precice/ci-images/blob/master/ci-aste.dockerfile
> Cache VTK build in ASTE CI
