precice/aste

CMakeLists.txt
src/partition_mesh.py

- Make METIS optional in CMakeLists
- Issue warning when METIS is used without topology
- Improve uniform algorithm
- Fix Eigen3 includes

Minor improvements

---

src/preciceMap.cpp

According to precice/precice#614

Port to preCICE v2 single-step setup

---

docs/README.md

With this I attempt to make it a bit clearer how to run the bundled demo.
However, I am not very sure on what I should see/understand in ParaView with the bunny & redblood cell example. Here is what I get if I follow the steps I added in the README.md:
Feel free to comment on what else we should explain. This is not meant to be a full tutorial: that will hopefully follow soon.

Clarify how to run and visualize the demo

---

contrib/demo.sh
docs/README.md

The [contrib/demo.sh](https://github.com/precice/aste/blob/mapping-tests/contrib/demo.sh) is currently out-of-date with the mapping-tests branch, leading to:
```shell
$ join_mesh.py mapped -i rbc.vtk -o result.vtk
usage: join_mesh.py [-h] [--out OUT_MESHNAME] [-r RECOVERY] [--numparts NUMPARTS] [--log {DEBUG,INFO,WARNING,ERROR,CRITICAL}] inputmesh
join_mesh.py: error: unrecognized arguments: -i rbc.vtk
```
I do not really understand how to modify it. I understand that it should be something like:
```shell
join_mesh.py -o result.vtk -r colored.dt0 -n 2 <output of preciceMapping>
```
I made it work with `rbc.vtk` as `<output of preciceMapping>`, but this is not correct. 
<details><summary>I tried with `mapped` (the directory), but it  also complains: (click)</summary>
```shell
$ …
```

Attempt to update demo.sh for the mapping-tests

---

src/mesh.cpp
src/mesh.hpp
src/preciceMap.cpp

Supported Cell Types: Triangle and Line(Edge)
Added support for Quadrilateral elements.

Support for Connectivity Information and VTK format Output

---

src/mesh.cpp

Change to obey preCICE exports and new partitioner.
https://github.com/precice/precice/pull/1126

Fix naming convention

---

src/common.cpp
src/mesh.cpp

ASTE has a problem with reading XML files. vtkGenericDataObjectReader cannot handle XML files
This PR changes Generic Reader to XML and Legacy readers depending on file extension.

Fix precicemap reader

---

src/partition_mesh.py

Fix mesh prefix in vtk partitioner

---

contrib/mapping-tester/generate.py
contrib/mapping-tester/plotstats.py
contrib/mapping-tester/preparemeshes.py
contrib/mapping-tester/setup-turbine-big.json
contrib/mapping-tester/setup-turbine-small-tps.json
contrib/mapping-tester/setup-turbine-small.json
contrib/mapping-tester/setup.json

Update mapping-tester according to updated CLI

---

CMakeLists.txt
src/partition_mesh.py

ASTE was lack of install option which increases usability. 
This PR provides an install option for ASTE and extends it for macOS.
Closes #54

Add install option for ASTE 

---

src/vtk_calculator.py

While error calculation `vtk_calculator` was not taking the absolute value of the error. This PR fixes this error.
Closes #87

Add missing abs for difference/error

---

src/join_mesh.py
src/partition_mesh.py
src/vtk_calculator.py

All ASTE tools were written in a procedural programming approach which is hard to maintain this PR changes this to OOP approach.

Refactor Tools

---

src/mesh.cpp
src/mesh.hpp
src/modes.cpp
src/partition_mesh.py
src/tests/write_test.cpp

In mapper mode `--output` is not working it was removed while adding replay mode.
This PR fix this issue

Add missing output in mapper mode

---

src/partition_mesh.py

ASTE partitioner has some functions inside the functions which are decorated as static method unnecessarily and causes some problem #113. This PR removes decorators

Remove static method decorator from inner functions

---

tools/mapping-tester/plotconv.py

... in order to have more flexibility.

Add a prefix for the plot script

---

tests/example/run-all.sh

Run all script of test examples was not exit on error in any run script.
This version catch errors in subscripts.
See :https://github.com/precice/aste/pull/130

Exit on error in run all script

---

.github/dependency_bot.yml

A bot regularly updates actions to keep up the GitHub CI up-to-date.

Add dependency bot

---

src/precice-aste-evaluate
src/precice-aste-join
src/precice-aste-partition

Python loggers are changed but get logger functions were not changed. This fixes logging problems of python scripts

Fix wrong logger names

---

src/mesh.cpp
src/mesh.hpp
src/modes.cpp
src/precice-aste-evaluate
src/precice-aste-join
src/precice-aste-partition
src/utilities.cpp

Some minor improvements regarding code quality and performance.
Main changes:
- Python variables are changed to pythonized form
- Exception classes added to Python scripts
- Variable declaration in C++ changed to a separate declaration.
- Some for loops change to reference version to avoid copy.
- `push_back` operations changed to `emplace_back` 
-  Some shadow declarations are removed.

Refactoring the code

---

src/configreader.cpp
src/mesh.cpp
src/metisAPI.cpp
src/modes.cpp
src/utilities.cpp

Fix -Wall -Wextra -Wno-unused-parameter compiler warnings

---

docs/README.md

Add exemplary instruction for ASTE replay mode

---

.github/workflows/aste_ci.yml

Update preCICE packages in CI

---

src/modes.cpp

Related to precice/precice#1366

Merge `initialize` and `initializeData`

---

docs/README.md

to create more transparency with ongoing VTK package issues.

Update docs for current VTK issues

---

.github/workflows/aste_ci.yml
docs/README.md
requirements.txt

Clean-up python requirements

---

.github/workflows/aste_ci_mac.yml
tools/mapping-tester/config-template.xml
tools/mapping-tester/generate.py

..in addition to ubuntu. Main motivation is to ensure compatibility with VTK and other utilities, potentially even giving installation instructions.

Add macOS CI for ASTE

---

changelog-entries/209.md
tools/mapping-tester/README.md

This PR adds documentation for the mapping-tester

Add documentation for mapping-tester
